
let podcastData = [
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title A',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title B',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title C',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title D',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title E',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title A',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title B',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title C',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title D',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title E',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title A',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title B',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title C',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title D',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title E',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title A',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title B',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title C',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title D',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title E',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title A',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title B',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title C',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title D',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title E',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title A',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title B',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title C',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title D',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title E',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title A',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title B',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title C',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title D',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title E',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title A',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title B',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title C',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title D',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title E',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title A',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title B',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title C',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title D',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title E',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title A',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title B',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title C',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title D',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title E',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title A',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title B',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title C',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title D',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title E',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title A',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title B',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title C',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title D',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title E',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title A',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title B',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title C',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title D',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title E',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title A',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title B',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title C',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title D',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title E',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title A',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title B',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title C',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title D',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title E',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title A',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title B',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title C',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title D',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title E',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title A',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title B',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title C',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title D',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title E',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title A',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title B',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title C',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title D',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title E',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title A',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title B',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title C',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title D',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title E',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title A',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title B',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:123,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title C',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:61,
	},
	{
		playedbefore:false,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title D',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:true,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:60,
	},
	{
		playedbefore:true,
		arturl:'albumart.jpg',
		title:'This Specific Podcast Episode Is Named Episode Title E',
		description:'Episode X description goes here. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, veniam eligendi quos nihil dignissimos doloremque, officia est quas explicabo deleniti repellendus iste tenetur magnam animi quis sapiente nam aut. Facere.',
		isexplicit:false,
		date:{
			y:2022,
			m:1,
			d:11,
		},
		lengthmin:59,
	},
]
