

// Define president data. 
const presidentData = [
	{
		posttype:'president',
		presidentid:1,
		title:'George Washington',
		content:'Hello there world',
		usevisual:true,
		photourl:'./../resources/images/presidents/01.jpg',
	},
	{
		posttype:'president',
		presidentid:2,
		title:'John Adams',
		content:'Hello there world',
		usevisual:true,
		photourl:'./../resources/images/presidents/02.jpg',
	},
	{
		posttype:'president',
		presidentid:3,
		title:'Thomas Jefferson',
		content:'Hello there world',
		usevisual:true,
		photourl:'./../resources/images/presidents/03.jpg',
	},
	{
		posttype:'president',
		presidentid:5,
		title:'James Monroe',
		content:'Hello there world',
		usevisual:true,
		photourl:'./../resources/images/presidents/05.jpg',
	},
	{
		posttype:'president',
		presidentid:6,
		title:'John Quincy Adams',
		content:'Hello there world',
		usevisual:true,
		photourl:'./../resources/images/presidents/06.jpg',
	},
	{
		posttype:'president',
		presidentid:7,
		title:'Andrew Jackson',
		content:'Hello there world',
		usevisual:true,
		photourl:'./../resources/images/presidents/07.jpg',
	},
	{
		posttype:'president',
		presidentid:11,
		title:'James K. Polk',
		content:'Hello there world',
		usevisual:true,
		photourl:'./../resources/images/presidents/11.jpg',
	},
	{
		posttype:'president',
		presidentid:16,
		title:'Abraham Lincoln',
		content:'Hello there world',
		usevisual:true,
		photourl:'./../resources/images/presidents/16.jpg',
	},
	{
		posttype:'president',
		presidentid:17,
		title:'Andrew Johnson',
		content:'Hello there world',
		usevisual:true,
		photourl:'./../resources/images/presidents/17.jpg',
	},
	{
		posttype:'president',
		presidentid:20,
		title:'James A. Garfield',
		content:'Hello there world',
		usevisual:true,
		photourl:'./../resources/images/presidents/20.jpg',
	},
	{
		posttype:'president',
		presidentid:21,
		title:'Calvin Coolidge',
		content:'Hello there world',
		usevisual:true,
		photourl:'./../resources/images/presidents/21.jpg',
	},
	{
		posttype:'president',
		presidentid:24,
		presidentid:22,
		title:'Grover Cleveland',
		content:'Hello there world',
		usevisual:true,
		photourl:'./../resources/images/presidents/22.jpg',
	},
	{
		posttype:'president',
		presidentid:23,
		title:'Benjamin Harrison',
		content:'Hello there world',
		usevisual:true,
		photourl:'./../resources/images/presidents/23.jpg',
	},
	{
		posttype:'president',
		presidentid:25,
		title:'Woodrow Wilson',
		content:'Hello there world',
		usevisual:true,
		photourl:'./../resources/images/presidents/28.jpg',
	},
	{
		posttype:'president',
		presidentid:26,
		title:'Theodoore Roosevelt',
		content:'Hello there world',
		usevisual:true,
		photourl:'./../resources/images/presidents/26.jpg',
	},
	{
		posttype:'president',
		presidentid:32,
		title:'Franklin D. Roosevelt',
		content:'Hello there world',
		usevisual:true,
		photourl:'./../resources/images/presidents/32.jpg',
	},
	{
		posttype:'president',
		presidentid:34,
		title:'Harry S. Truman',
		content:'Hello there world',
		usevisual:true,
		photourl:'./../resources/images/presidents/33.jpg',
	},
	{
		posttype:'president',
		presidentid:35,
		title:'John F. Kennedy',
		content:'Hello there world',
		usevisual:true,
		photourl:'./../resources/images/presidents/35.jpg',
	},
	{
		posttype:'president',
		presidentid:36,
		title:'Lyndon B. Johnson',
		content:'Hello there world',
		usevisual:true,
		photourl:'./../resources/images/presidents/36.jpg',
	},
	{
		posttype:'president',
		presidentid:37,
		title:'Richard M. Nixon',
		content:'Hello there world',
		usevisual:true,
		photourl:'./../resources/images/presidents/37.jpg',
	},
	{
		posttype:'president',
		presidentid:38,
		title:'Gerald R. Ford',
		content:'Hello there world',
		usevisual:true,
		photourl:'./../resources/images/presidents/38.jpg',
	},
	{
		posttype:'president',
		presidentid:39,
		title:'James Carter',
		content:'Hello there world',
		usevisual:true,
		photourl:'./../resources/images/presidents/39.jpg',
	},
	{
		posttype:'president',
		presidentid:40,
		title:'Ronald Reagan',
		content:'Hello there world',
		usevisual:true,
		photourl:'./../resources/images/presidents/40.jpg',
	},
	{
		posttype:'president',
		presidentid:41,
		title:'George H.W. Bush',
		content:'Hello there world',
		usevisual:true,
		photourl:'./../resources/images/presidents/41.jpg',
	},
	{
		posttype:'president',
		presidentid:42,
		title:'Bill Clinton',
		content:'Hello there world',
		usevisual:true,
		photourl:'./../resources/images/presidents/42.jpg',
	},
	{
		posttype:'president',
		presidentid:43,
		title:'George W. Bush',
		content:'Hello there world',
		usevisual:true,
		photourl:'./../resources/images/presidents/43.jpg',
	},
	{
		posttype:'president',
		presidentid:44,
		title:'Barack Obama',
		content:'Hello there world',
		usevisual:true,
		photourl:'./../resources/images/presidents/44.jpg',
	},
	{
		posttype:'president',
		presidentid:45,
		title:'Donald Trump',
		content:'Hello there world',
		usevisual:true,
		photourl:'./../resources/images/presidents/45.jpg',
	},
	{
		posttype:'president',
		presidentid:46,
		title:'Joseph Biden',
		content:'Hello there world',
		usevisual:true,
		photourl:'./../resources/images/presidents/46.jpg',
	},
];

