


// Define user data. 
const userData = [

	{
		userid:'xyzabcxyz',
		fname:'Ace',
		lname:'Ventura',
		avatarurl:'assets/images/avatar-m.png',
	},
	{
		userid:'xyzabcxyz',
		fname:'Bill',
		lname:'Diamond',
		avatarurl:'assets/images/avatar-m.png',
	},
	{
		userid:'xyzabcxyz',
		fname:'Christine',
		lname:'Brophy',
		avatarurl:'assets/images/avatar-f.png',
	},
	
	{
		userid:'xyzabcxyz',
		fname:'David',
		lname:'Doe',
		avatarurl:'assets/images/avatar-m.png',
	},
	{
		userid:'xyzabcxyz',
		fname:'Eli',
		lname:'Doe',
		avatarurl:'assets/images/avatar-m.png',
	},
	{
		userid:'xyzabcxyz',
		fname:'Fred',
		lname:'Doe',
		avatarurl:'assets/images/avatar-m.png',
	},
	{
		userid:'xyzabcxyz',
		fname:'George',
		lname:'Doe',
		avatarurl:'assets/images/avatar-m.png',
	},
	{
		userid:'xyzabcxyz',
		fname:'Hilary',
		lname:'Doe',
		avatarurl:'assets/images/avatar-f.png',
	},
	{
		userid:'xyzabcxyz',
		fname:'Ian',
		lname:'Doe',
		avatarurl:'assets/images/avatar-m.png',
	},
	{
		userid:'xyzabcxyz',
		fname:'Jane',
		lname:'Doe',
		avatarurl:'assets/images/avatar-f.png',
	},
	{
		userid:'xyzabcxyz',
		fname:'Jay',
		lname:'Doe',
		avatarurl:'assets/images/avatar-m.png',
	},
	{
		userid:'xyzabcxyz',
		fname:'Jenny',
		lname:'Doe',
		avatarurl:'assets/images/avatar-f.png',
	},
	{
		userid:'xyzabcxyz',
		fname:'Jill',
		lname:'Doe',
		avatarurl:'assets/images/avatar-f.png',
	},
	{
		userid:'xyzabcxyz',
		fname:'Jim',
		lname:'Doe',
		avatarurl:'assets/images/avatar-m.png',
	},
	{
		userid:'xyzabcxyz',
		fname:'Joe',
		lname:'Doe',
		avatarurl:'assets/images/avatar-m.png',
	},
	{
		userid:'xyzabcxyz',
		fname:'John',
		lname:'Doe',
		avatarurl:'assets/images/avatar-m.png',
	},
	{
		userid:'xyzabcxyz',
		fname:'Kate',
		lname:'Doe',
		avatarurl:'assets/images/avatar-f.png',
	},
	{
		userid:'xyzabcxyz',
		fname:'Leah',
		lname:'Doe',
		avatarurl:'assets/images/avatar-f.png',
	},
	{
		userid:'xyzabcxyz',
		fname:'Mike',
		lname:'Doe',
		avatarurl:'assets/images/avatar-m.png',
	},
	{
		userid:'xyzabcxyz',
		fname:'Nina',
		lname:'Doe',
		avatarurl:'assets/images/avatar-f.png',
	},
	{
		userid:'xyzabcxyz',
		fname:'Oscar',
		lname:'Doe',
		avatarurl:'assets/images/avatar-m.png',
	},
	{
		userid:'xyzabcxyz',
		fname:'Peter',
		lname:'Doe',
		avatarurl:'assets/images/avatar-m.png',
	},
	{
		userid:'xyzabcxyz',
		fname:'Quinten',
		lname:'Doe',
		avatarurl:'assets/images/avatar-m.png',
	},
	{
		userid:'xyzabcxyz',
		fname:'Rachel',
		lname:'Doe',
		avatarurl:'assets/images/avatar-f.png',
	},
	{
		userid:'xyzabcxyz',
		fname:'Steve',
		lname:'Doe',
		avatarurl:'assets/images/avatar-m.png',
	},
	{
		userid:'xyzabcxyz',
		fname:'Tim',
		lname:'Doe',
		avatarurl:'assets/images/avatar-m.png',
	},
	{
		userid:'xyzabcxyz',
		fname:'Tori',
		lname:'Doe',
		avatarurl:'assets/images/avatar-f.png',
	},
	{
		userid:'xyzabcxyz',
		fname:'Ursula',
		lname:'Doe',
		avatarurl:'assets/images/avatar-f.png',
	},
	{
		userid:'xyzabcxyz',
		fname:'Victor',
		lname:'Doe',
		avatarurl:'assets/images/avatar-m.png',
	},
	{
		userid:'xyzabcxyz',
		fname:'Wendy',
		lname:'Doe',
		avatarurl:'assets/images/avatar-f.png',
	},
	{
		userid:'xyzabcxyz',
		fname:'Xavier',
		lname:'Doe',
		avatarurl:'assets/images/avatar-m.png',
	},
	{
		userid:'xyzabcxyz',
		fname:'Yolanda',
		lname:'Doe',
		avatarurl:'assets/images/avatar-f.png',
	},

];


// Define user occupation data. 
const userOccupationData = [

	// 

];
